# Hadolint configuration
# https://github.com/hadolint/hadolint

ignored:
  - DL3018  # Pin versions in apk add - ignoring for development simplicity
  - DL3007  # Using latest tag - acceptable for base alpine image in this context
