# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false  # Disable line length check for documentation

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false  # Some files may not start with a heading

# Allow inline HTML
MD033: false
