# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Security - Prevent secrets from being committed
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks protect --verbose --redact --staged
        language: golang
        pass_filenames: false

  # Go-specific hooks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: go fmt
        description: Run 'go fmt' on all Go files
      - id: go-vet
        name: go vet
        description: Run 'go vet' on all Go files
      - id: go-mod-tidy
        name: go mod tidy
        description: Run 'go mod tidy' to clean up dependencies
      - id: go-unit-tests
        name: go test
        description: Run Go unit tests
      - id: golangci-lint
        name: golangci-lint
        description: Run golangci-lint

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensure files end with a newline
      - id: check-yaml
        name: Check YAML
        description: Check YAML files for syntax errors
      - id: check-json
        name: Check JSON
        description: Check JSON files for syntax errors
      - id: check-added-large-files
        name: Check for large files
        description: Prevent large files from being committed
        args: ['--maxkb=5000']
      - id: check-case-conflict
        name: Check case conflicts
        description: Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict
        name: Check merge conflicts
        description: Check for files that contain merge conflict strings
      - id: detect-private-key
        name: Detect private keys
        description: Detect presence of private keys
      - id: check-executables-have-shebangs
        name: Check executables have shebangs
        description: Ensure executables have proper shebangs
      - id: check-symlinks
        name: Check symlinks
        description: Check for symlinks which point to nothing

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: markdownlint
        description: Check markdown files for style issues
        args: ['--fix']

  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Lint Dockerfiles with hadolint

  # YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        description: Lint YAML files
        args: ['--strict', '-d', '{extends: relaxed, rules: {line-length: {max: 120}}}']

# Optional: Commit message format checker
# Uncomment if you want to enforce conventional commits
# - repo: https://github.com/commitizen-tools/commitizen
#   rev: v3.29.1
#   hooks:
#     - id: commitizen
#       stages: [commit-msg]
